title: Service
type: object
additionalProperties: false
required:
  - apiVersion
  - kind
  - name
  - build
  - deploy
properties:
  apiVersion:
    $ref: './partials/api-version.yaml'
  kind:
    const: 'Service'
  name:
    $ref: './partials/name.yaml'
  build:
    type: object
    additionalProperties: false
    required:
      - artifacts
      - tags
    properties:
      artifacts:
        type: object
        required:
          - toBuild
          - toPush
        properties:
          toBuild:
            $ref: '#/$defs/entries'
          toPush:
            $ref: '#/$defs/entries'
      tags:
        $ref: '#/$defs/entries'
  deploy:
    type: object
    additionalProperties: false
    required:
      - releases
    properties:
      releases:
        $ref: '#/$defs/entries'
  run:
    type: object
    additionalProperties: false
    required:
      - tasks
    properties:
      tasks:
        type: object
        additionalProperties:
          $ref: '#/$defs/entries'
        tsType: 'Record<string, ({ index: number, type: string, spec: unknown })[] | undefined>'
$defs:
  entries:
    type: array
    items:
      type: object
      additionalProperties: false
      required:
        - index
        - type
        - spec
      properties:
        index:
          type: integer
        type:
          type: string
        spec: {}
