apiVersion: g2a-cli/v2.0
kind: Deployer
name: artifactory
schema:
  type: object
  required:
    - source
    - target
  properties:
    source:
      type: string
      minLength: 1
    target:
      type: string
      minLength: 1
script: |
  throw "not implemented"
