apiVersion: g2a-cli/v2.0
kind: Deployer
name: script
schema:
  type: object
  required:
    - sh
  properties:
    sh:
      type: string
script: |
  exec := import("exec")
  exec.run("sh", "-c", input.spec.sh)
