apiVersion: g2a-cli/v2.0
kind: Builder
name: docker
schema:
  type: object
  required:
    - image
  properties:
    image:
      type: string
    context:
      type: string
    dockerfilePath:
      type: string
    buildTarget:
      type: string
    buildArgs:
      type: object
      additionalProperties:
        type: string
script: |
  exec := import("exec")

  for tag in input.tags {
    image := input.spec.image + ":" + tag
    args := [ "build", input.spec.context || ".", "-t", image ]

    if input.spec.dockerfilePath {
      args += [ "-f", input.spec.dockerfilePath ]
    }

    for (let key in input.spec.buildArgs) {
      args += [ "--build-arg", key + "=" + input.spec.buildArgs[key] ]
    }

    if input.spec.buildTarget {
      args += [ "--target", input.spec.buildTarget ]
    }

    exec.command({
      name: "docker",
      args: args,
      dir: input.dirs.service
    }).run()

    addResult(image)
  }
