apiVersion: g2a-cli/v2.0
kind: Builder
name: script
schema:
  type: object
  required:
    - sh
  properties:
    sh:
      type: string
script: |
  exec('sh', [ '-c', 'export PUSH=false\n' + input.spec.sh ])
