apiVersion: g2a-cli/v2.0
kind: Builder
name: script
schema:
  type: object
  required:
    - sh
  properties:
    sh:
      type: string
script: |
  exec := import("exec")
  opts := {
    name: "sh",
    args: [ "-c", input.spec.sh ],
    env: [ "PUSH=false" ]
  }
  exec.command(opts).run()
