---
apiVersion: g2a-cli/v2.0
kind: Tagger
name: custom
schema:
  type: string
  minLength: 1
script: |
  addResult(input.spec)
---
apiVersion: g2a-cli/v2.0
kind: Builder
name: docker
schema:
  type: object
  required:
    - image
  properties:
    image:
      type: string
# Since it's only an example, this builder doesn't do anything interesting.
script: |
  for tag in input.tags {
    addResult(input.spec.image + ":" + tag)
  }
---
apiVersion: g2a-cli/v2.0
kind: Pusher
name: docker
schema:
  type: object
# Since it's only an example, this builder doesn't do anything interesting.
script: |
  addResult(input.artifacts...)
---
apiVersion: g2a-cli/v2.0
kind: Deployer
name: helm
schema:
  type: object
  required:
    - name
    - chartPath
  properties:
    name:
      type: string
    chartPath:
      type: string
    chartVersion:
      type: string
    values:
      type: object
      additionalProperties:
        type: string
    chartRepository:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        url:
          type: string
# Since it's only an example, this builder doesn't do anything interesting.
script: |
  addResult(input.spec.name)
