apiVersion: g2a-cli/v2.0
kind: Tagger
name: custom
schema:
  oneOf:
    - type: object
      required:
        - format
      properties:
        format:
          type: string
          minLength: 1
    - type: string
      minLength: 1
script: |
  let tag = typeof input.spec === 'string' ? input.spec : input.spec.format
  output.push(tag)
