apiVersion: g2a-cli/v2.0
kind: Tagger
name: custom
schema:
  oneOf:
    - type: object
      required:
        - format
      properties:
        format:
          type: string
          minLength: 1
    - type: string
      minLength: 1
script: |
  if is_string(input.spec) {
    addResult(input.spec)
  } else {
    addResult(input.spec.format)
  }
