apiVersion: g2a-cli/v2.0
kind: Tagger
name: gitSha
schema:
  type: object
  properties:
    length:
      type: integer
      min: 1
      max: 40
script: |
  exec := import("exec")
  result := exec.command("git", "log", "-1", "--pretty=format:%H").must_output()
  addResult(result[0:40])
