---
apiVersion: g2a-cli/v1beta4
kind: Service
name: service
hooks:
  pre-build:
    - echo pre-build
  post-build:
    - echo post-build
  pre-deploy:
    - echo pre-deploy
  post-deploy:
    - echo post-deploy
build:
  artifacts:
    - script:
        sh: |
          echo ..:: build ::..
          echo param: {{ .Params.Param }}
  tagPolicy:
    # Usually it's better to use tag policies like "gitSha" or "gitTag", but we
    # need to test these examples, so tags should not change.
    custom:
      format: "latest"
deploy:
  releases:
    - script:
        sh: |
          echo ..:: deploy ::..
          echo tag: {{ .Opts.Tag }}
          echo environment var: {{ .Env.Variable }}
          echo param: {{ .Params.Param }}
